### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by brandon-leapyear** [8c6794b6/hpc-codecov#1]
Hello, just writing this ticket to express my disappointment that you beat me to this haha. I've been working on this at https://github.com/LeapYear/hpc-codecov.

Maybe we could merge efforts somehow? I might also change gears and see about generating an lcov report instead, which should be more general to other coverage services

**Comment by 8c6794b6** [comment]
Wow ... what a coincidence :astonished:

> Maybe we could merge efforts somehow?

Sure, if you have any idea, I'm happy to hear.

> I might also change gears and see about generating an lcov report instead, which should be more general to other coverage services

I once thought about lcov (and gcov) too, since Codecov and [Code Climate](https://codeclimate.com/) support those formats.  It shall be useful if one prefers other services than Codecov.

I also thought about something like *pandoc-for-code-coverage*. However, after a bit more thought, I couldn't convince myself with meaningful use of such general-purpose code coverage utility. Maybe I'm wrong, and not sure whether similar utilities already exist.
